#!/bin/sh

export MIRROR_BOOTSTRAP=localhost:3142
export MIRROR_BINARY=http.debian.net

lb config noauto \
    --clean \
    --ignore-system-defaults \
    --architectures i386 \
    --mode debian \
    --distribution sid \
    --archive-areas "main contrib non-free" \
    --bootappend-live "boot=live config hostname=skeeto username=skeeto" \
    --debian-installer false \
    --debian-installer-gui false \
    --iso-application "Skeeto Live" \
    --iso-publisher "skeeto" \
    --iso-volume "skeeto-"$(date +%Y%m%d) \
    --mirror-bootstrap        http://$MIRROR_BOOTSTRAP/debian/ \
    --mirror-chroot-security  http://$MIRROR_BOOTSTRAP/debian-security/ \
    --mirror-chroot-backports http://$MIRROR_BOOTSTRAP/debian-backports/ \
    --mirror-binary           http://$MIRROR_BINARY/debian/ \
    "${@}"
