#!/bin/sh

lb config noauto \
    --clean \
    --ignore-system-defaults \
    --architectures i386 \
    --mode debian \
    --distribution sid \
    --archive-areas "main contrib non-free" \
    --bootappend-live "boot=live config username=skeeto" \
    --debian-installer false \
    --debian-installer-gui false \
    --iso-application "Skeeto Live" \
    --iso-publisher "skeeto" \
    --iso-volume "skeeto-"$(date +%Y%m%d) \
    --mirror-bootstrap        http://localhost:3142/debian/ \
    --mirror-chroot-security  http://localhost:3142/debian-security/ \
    --mirror-chroot-backports http://localhost:3142/debian-backports/ \
    --mirror-binary           http://http.debian.net/debian/ \
    "${@}"
