#!/bin/sh

MIRROR_BOOTSTRAP=localhost:3142
MIRROR_BINARY=http.debian.net

KPARAMS="mitigations=off hostname=skeeto username=wellons noeject"

lb config noauto \
    --clean \
    --ignore-system-defaults \
    --architectures amd64 \
    --mode debian \
    --distribution bullseye \
    --archive-areas "main contrib non-free" \
    --bootappend-live "boot=live config $KPARAMS" \
    --debian-installer none \
    --debian-installer-gui false \
    --iso-application "Skeeto Live" \
    --iso-publisher "skeeto" \
    --iso-volume "skeeto-"$(date +%Y%m%d) \
    --security true \
    --mirror-bootstrap        http://$MIRROR_BOOTSTRAP/debian/ \
    --mirror-chroot           http://$MIRROR_BOOTSTRAP/debian/ \
    --mirror-chroot-security  http://$MIRROR_BOOTSTRAP/security.debian.org/ \
    --mirror-binary           http://$MIRROR_BINARY/debian/ \
    "${@}"
