#!/bin/sh

export CONF=/etc/skeeto

sudo -u skeeto -H /bin/sh <<EOF
cd

if [ -e .live-installed ]; then
    exit 0;
else
    touch .live-installed
fi

git clone $CONF/dotfiles .dotfiles
cd .dotfiles
./install.sh -p
git remote set-url origin https://github.com/skeeto/dotfiles.git
cd ..
cp -r $CONF/misc .wallpaper/

EOF
