#!/bin/sh

export CONF=/etc/skeeto
cd /home/skeeto

sudo -u skeeto -H git clone $CONF/emacs.d.git .emacs.d
cd .emacs.d
tar -xf $CONF/elpa.tar.gz
cd ..

sudo -u skeeto -H git clone $CONF/dotfiles .dotfiles
cd .dotfiles
sudo -u skeeto -H ./install.sh -p
cd ..
sudo -u skeeto -H cp -r $CONF/misc .wallpaper/
